package yuriy.labs.labs_2.labs_2_10_.l_2_11.l_2_11_1__2.TestException;

/**
 * Created by Ruble on 31.05.2017.
 */
public class MyException {
  /*  try {
        int i = 0;
    }
        catch (Exception e)
    {
        System.out.println("Exception");
    }
        finally {
        System.out.println("Finally");
    }*/
}
